name: Deploy website
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <preview|production>"
        required: true
        default: "preview"
jobs:
  deploy:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./site
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npm install && npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./site/out --project-name=pikatorrent-site --branch=${{ github.event.inputs.environment == 'production' && 'main' || 'preview' }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
